name: roblox_portfolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Google
      fonts:
        - asset: fonts/google-sans/ProductSans-Regular.ttf
        - asset: fonts/google-sans/ProductSans-Bold.ttf
          weight: 700
        - asset: fonts/google-sans/ProductSans-Italic.ttf
          style: italic

  assets:
    - assets/
